services:

  app:
    image: pedroavenir/adslabs-restaurante
    container_name: adslabs_restaurante
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: db
      PORT: ${PORT}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: adslabs_restaurante_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: